package gui;

import javax.swing.*;
import javax.swing.border.EmptyBorder;
import java.awt.*;

public class ShowManagementWindow {
    public static JButton buttonCreateCustomer;
    public static JButton buttonFindCustomer;
    public static JButton buttonCreateCard;
    public static JButton buttonCloseCard;
    public static JTextField clientName;
    public static JTextField clientLastName;
    public static JTextField clientBirthDateY;
    public static JTextField clientBirthDateM;
    public static JTextField clientBirthDateD;
    public static JTextField clientEmail;
    public static JLabel labelClientCards;
    public static JTextArea clientCards;

    public ShowManagementWindow(){
        JFrame frameAddNewUser = new JFrame("Management");
        frameAddNewUser.setBounds(100, 20, 750, 400);
//        frameAddNewUser.setResizable(false);
        frameAddNewUser.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frameAddNewUser.setLayout(new BorderLayout());

        JPanel top = new JPanel();
        top.setBorder(new EmptyBorder(20, 0, 0, 0));
        JLabel labelUser = new JLabel("Информация о клиенте");
        labelUser.setFont(new Font("Arial", Font.BOLD, 20));
        top.add(labelUser);

        JPanel panel = new JPanel();
        panel.setLayout(new GridBagLayout());
        JLabel labelUserName = new JLabel("Имя клиента:");
        JLabel labelUserLastName = new JLabel("Фамилия:");
        JLabel labelUserBirthDate = new JLabel("Дата рождения:");
        JLabel labelUserEmail = new JLabel("email клиента:");
        labelClientCards = new JLabel("Карты клиента");
        clientName = new JTextField();
        Dimension textFieldDimension = new Dimension(150, 20);
        clientName.setPreferredSize(textFieldDimension);
        clientLastName = new JTextField();
        clientLastName.setPreferredSize(textFieldDimension);
        clientBirthDateY = new JTextField();
        clientBirthDateY.setPreferredSize(new Dimension(50, 20));
        JLabel labelY = new JLabel("Год");
        clientBirthDateM = new JTextField();
        clientBirthDateM.setPreferredSize(new Dimension(50, 20));
        JLabel labelM = new JLabel("Месяц");
        clientBirthDateD = new JTextField();
        clientBirthDateD.setPreferredSize(new Dimension(50, 20));
        JLabel labelD = new JLabel("День");
        clientEmail = new JTextField();
        clientEmail.setPreferredSize(textFieldDimension);
        clientCards = new JTextArea("XXXX XXXX XXXX XXXX");

        GridBagConstraints c = new GridBagConstraints();
        c.fill = GridBagConstraints.BOTH;
        c.insets = new Insets(0, 0, 5, 5);
        c.gridx = 0;
        c.gridy = 0;
        panel.add(labelUserName, c);
        c.gridx = 0;
        c.gridy = 1;
        panel.add(labelUserLastName, c);
        c.gridx = 0;
        c.gridy = 2;
        panel.add(labelUserBirthDate, c);
        c.gridx = 2;
        c.gridy = 2;
        panel.add(labelY, c);
        c.gridx = 2;
        c.gridy = 3;
        panel.add(labelM, c);
        c.gridx = 2;
        c.gridy = 4;
        panel.add(labelD, c);
        c.gridx = 0;
        c.gridy = 5;
        panel.add(labelUserEmail, c);
        c.gridx = 0;
        c.gridy = 6;
        panel.add(labelClientCards, c);
        c.gridx = 1;
        c.gridy = 0;
        panel.add(clientName, c);
        c.gridx = 1;
        c.gridy = 1;
        panel.add(clientLastName, c);
        c.gridx = 1;
        c.gridy = 2;
        panel.add(clientBirthDateY, c);
        c.gridx = 1;
        c.gridy = 3;
        panel.add(clientBirthDateM, c);
        c.gridx = 1;
        c.gridy = 4;
        panel.add(clientBirthDateD, c);
        c.gridx = 1;
        c.gridy = 5;
        panel.add(clientEmail, c);
        c.gridx = 1;
        c.gridy = 6;
        panel.add(clientCards, c);
        JPanel bottomPanel = new JPanel();
        bottomPanel.setBorder(new EmptyBorder(0, 0, 20, 0));
        buttonCreateCustomer = new JButton("Новый клиент");
        buttonFindCustomer = new JButton("Найти клиента");
        buttonCreateCard = new JButton("Новая карта");
        buttonCloseCard = new JButton("Аннулировать карту");
        bottomPanel.add(buttonCreateCustomer);
        bottomPanel.add(buttonFindCustomer);
        bottomPanel.add(buttonCreateCard);
        bottomPanel.add(buttonCloseCard);
        frameAddNewUser.add(top, BorderLayout.NORTH);
        frameAddNewUser.add(panel, BorderLayout.CENTER);
        frameAddNewUser.add(bottomPanel, BorderLayout.SOUTH);
        frameAddNewUser.setVisible(true);
    }
}
